"""Seed prototype prompts for the complexity classifier.

Three tiers: simple, medium, complex.
Used by both the binary classifier (simple vs complex centroids) and
the cascade classifier (ternary centroid classification).
"""

SIMPLE_PROTOTYPES = [
    "What is the capital of France?",
    "Who wrote Romeo and Juliet?",
    "What year did World War II end?",
    "How many continents are there?",
    "What is the chemical symbol for gold?",
    "What language do they speak in Brazil?",
    "Who painted the Mona Lisa?",
    "What is the largest planet in our solar system?",
    "What is the speed of light?",
    "How many sides does a hexagon have?",
    "What is 25 times 4?",
    "Calculate 150 divided by 3",
    "What is 17 plus 38?",
    "What is 10% of 250?",
    "Convert 5 kilometers to miles",
    "Define photosynthesis",
    "What does GDP stand for?",
    "What is an algorithm?",
    "Define the word 'serendipity'",
    "What is a metaphor?",
    "How do you say hello in Japanese?",
    "Translate 'thank you' to Spanish",
    "What is 'goodbye' in French?",
    "Is Python a compiled language?",
    "Does the Earth revolve around the Sun?",
    "Is 7 a prime number?",
    "Can penguins fly?",
    "Is HTML a programming language?",
    "Convert this text to uppercase: hello world",
    "List the days of the week",
    "Sort these numbers: 5, 2, 8, 1, 9",
    "What is today's date?",
    "Reverse the string 'hello'",
    "Hello, how are you?",
    "Good morning!",
    "Tell me a joke",
    "What's your name?",
    "What is the boiling point of water?",
    "What timezone is New York in?",
    "What is the population of Tokyo?",
    "How tall is Mount Everest?",
    "What is the atomic number of carbon?",
    "Summarize this in one sentence",
    "Give me a synonym for 'happy'",
    "What is the opposite of 'cold'?",
    "Name three primary colors",
    "What comes after Tuesday?",
    "Read the file config.yaml",
    "Show me the contents of README.md",
    "What's in the .env file?",
    "List all files in the src directory",
    "Find all Python files in this project",
    "Run npm install",
    "Check the git status",
    "What branch am I on?",
    "Show me the last 5 git commits",
    "Run the tests",
    "Search for the latest version of React",
    "What is the current price of Bitcoin?",
    "Look up the npm package express",
    "Fetch the docs for FastAPI Query parameters",
    "What does this function do?",
    "What's the syntax for a Python list comprehension?",
    "How do I create a new branch in git?",
    "What port is the server running on?",
    "Show me the imports in main.py",
    "Change the port from 3000 to 8080",
    "Add a newline at the end of this file",
    "Rename the variable x to count",
    "Fix this typo: 'recieve' should be 'receive'",
    "Remove the unused import on line 3",
    "What version of Node is installed?",
    "How much disk space is available?",
    "Is the database running?",
    "What's my IP address?",
    "Show the environment variables",
    # --- Business ---
    "What's the current exchange rate for USD to EUR?",
    "Define ROI",
    "What does B2B mean?",
    "What is a startup?",
    "What does CEO stand for?",
    # --- Legal ---
    "What is a non-disclosure agreement?",
    "Define breach of contract",
    "What's the difference between civil and criminal law?",
    "What does 'pro bono' mean?",
    "What is a patent?",
    # --- Creative ---
    "Write a haiku about spring",
    "Give me a synonym for 'happy'",
    "What rhymes with 'moon'?",
    "Name a famous painting",
    "What is alliteration?",
    # --- Education ---
    "What year did World War 2 end?",
    "What is photosynthesis?",
    "Name the planets in our solar system",
    "Who discovered penicillin?",
    "What is the Pythagorean theorem?",
    # --- Medical ---
    "What does BMI stand for?",
    "Normal human body temperature?",
    "What is an antibiotic?",
    "What does CPR stand for?",
    "How many bones are in the human body?",
    # --- Finance ---
    "What is compound interest?",
    "Define inflation",
    "What's a 401k?",
    "What does APR mean?",
    "What is a credit score?",
    # --- General knowledge ---
    "Translate 'hello' to Spanish",
    "What time is it in Tokyo?",
    "How many cups in a gallon?",
    "What is the speed of sound?",
    "How many days are in a leap year?",
    "What is the tallest building in the world?",
    "What is the currency of Japan?",
    "How many teaspoons in a tablespoon?",
    "What color do you get when you mix red and blue?",
    "Who wrote 'Pride and Prejudice'?",
]

MEDIUM_PROTOTYPES = [
    # --- Customer support / ops troubleshooting (single-issue, specific) ---
    "Our PostgreSQL read replica is lagging behind by 30 seconds during peak hours. Instance is db.r5.xlarge with 500 write transactions per second.",
    "SAML SSO with Okta gives 'Invalid SAML Response' error after user authenticates. Entity ID and ACS URL are configured.",
    "Kubernetes pods keep getting OOMKilled. Memory requests 256Mi, limits 512Mi, Java app with Xmx 450m.",
    "We need automated database backups retained for 90 days for HIPAA compliance. Currently only 7 days.",
    "Intermittent 502 errors on load balancer during rolling deployments, about 5% of requests fail.",
    "Need to migrate 500GB PostgreSQL database from us-east-1 to eu-west-1 with minimal downtime.",
    "Terraform deployment failing with 'Provider produced inconsistent result after apply' on kubernetes_cluster resource.",
    "How do we set up blue-green deployments for 3 services behind a load balancer?",
    "Webhook endpoint receiving duplicate events, same event ID arriving 2-3 times within 60 seconds.",
    "Need cross-region Redis replication for disaster recovery. Primary in us-east-1, replica in us-west-2.",
    "API rate limited at 1000 req/min but need 5000 req/min for nightly batch processing.",
    "High p99 latency over 2 seconds on GraphQL endpoint but p50 is fine at 200ms. Suspect N+1 queries.",
    "Need VPN between on-premises Cisco ASA and cloud VPC. What IPsec parameters to use?",
    "Auto-scaling group not scaling fast enough. Min 2, max 10, target CPU 70%, cooldown 300s but traffic spikes 10x in 2 minutes.",
    "Getting connection pool exhausted errors on managed PostgreSQL. 3 app servers with pool size 50, DB max connections 100.",
    "Help set up CI/CD with GitHub Actions. Deploy to staging on PR merge, production on tag push.",
    "CDN cache hit ratio dropped from 92% to 45% after a deploy. We use versioned assets with content hashing.",
    "Need to configure mTLS between microservices on Kubernetes. Istio vs native approach?",
    "SSL certificate renewal failing on load balancer. Using Let's Encrypt with auto-renewal.",
    "Database connection timeouts during peak load. Pool size 20, average query time 50ms.",
    "Redis cluster keeps losing data after node restart. Using RDB snapshots every 5 minutes.",
    "S3 bucket policy denying access despite IAM role having correct permissions. Cross-account access.",
    "Docker container crashes with signal 9 after running for exactly 30 minutes. Memory limit is 2GB.",
    "CloudWatch alarms not triggering even though metrics exceed threshold. Evaluation period 5 minutes.",
    "Load balancer health checks failing for 2 out of 8 targets. All targets respond to curl.",
    "Nginx returning 413 Request Entity Too Large for file uploads over 10MB. Need to support 100MB.",
    "DNS propagation taking over 48 hours after changing nameservers. TTL was set to 3600.",
    "RDS instance running out of storage. Currently 500GB, growing 5GB/day. Need automated solution.",
    "Application logs not appearing in centralized logging. Fluentd sidecar shows no errors.",
    "Prometheus scraping timeout for 3 services. Scrape interval 15s, timeout 10s, metrics endpoint returns in 8s.",
    # --- Coding tasks (moderate complexity, single-function or single-class) ---
    "Write a function to check if a string is a palindrome, handling edge cases like spaces and punctuation",
    "Explain the difference between SQL joins: INNER, LEFT, RIGHT, and FULL OUTER with examples",
    "Create a Python class for a linked list with insert, delete, and search methods",
    "Write a bash script that backs up a directory with timestamp naming and keeps only the last 5 backups",
    "Explain how DNS resolution works, from browser to response",
    "Write unit tests for a shopping cart class that handles adding, removing items and calculating totals",
    "Create a REST API endpoint in FastAPI that handles file uploads with validation",
    "Explain the difference between processes and threads with practical examples",
    "Write a React component for a sortable data table with pagination",
    "Implement a binary search tree with insert and in-order traversal in Python",
    "Create a Docker Compose file for a web app with Postgres and Redis services",
    "Write a Python script to parse CSV files and generate summary statistics",
    "Explain how HTTPS and TLS handshake works step by step",
    "Implement a rate limiter middleware in Express.js using Redis",
    "Write a regular expression to validate email addresses and explain each part",
    "Create a GitHub Actions workflow for CI/CD that runs tests and deploys to staging",
    "Explain the event loop in Node.js with code examples showing blocking vs non-blocking operations",
    "Write a Python decorator that caches function results with TTL expiration",
    "Create a responsive navigation component with a hamburger menu for mobile using React and Tailwind",
    "Implement depth-first and breadth-first search for a graph in Python",
    # --- DevOps / infrastructure (moderate scope) ---
    "Write a Terraform configuration to provision an EC2 instance with a security group",
    "Explain how garbage collection works in JavaScript including mark-and-sweep",
    "Create an authentication middleware in FastAPI that validates JWT tokens",
    "Write a Python script to interact with the GitHub API to list and create issues",
    "Implement a simple pub/sub system in Python using asyncio",
    "Compare and contrast REST vs GraphQL with pros and cons for each",
    "Write a SQL query to find the top 3 customers by total spending with their most purchased product",
    "Create a TypeScript utility type that makes all nested properties optional",
    "Implement a simple state machine in Python for an order processing workflow",
    "Write a blog post outline about the benefits of microservices",
    # --- Conceptual explanations (deeper than simple, narrower than complex) ---
    "Explain the SOLID principles with code examples for each principle",
    "Create a Python context manager for database connections with error handling",
    "Write a shell script that monitors CPU and memory usage and sends alerts when thresholds are exceeded",
    "Implement a simple web scraper in Python that extracts product data from an HTML page",
    "Create a Kubernetes manifest for deploying a web application with 3 replicas",
    "Write a function to flatten a deeply nested JSON object into dot-notation keys",
    "Explain how React hooks work internally, focusing on useState and useEffect",
    "Create a Python logging configuration with file rotation, formatting, and multiple handlers",
    "Summarize the key points of this research paper in 3 paragraphs",
    "Write a comparison of 5 popular CSS frameworks highlighting their trade-offs",
    # --- Data / scripting tasks ---
    "Create a data migration script that transforms records from one schema to another",
    "Explain how WebSocket connections work and implement a simple chat server",
    "Write a Python function to merge two sorted arrays efficiently",
    "Create an OpenAPI spec for a todo list API with CRUD operations",
    "Debug this React component that re-renders infinitely and explain the fix",
    "Write a Makefile for a Go project with build, test, lint, and clean targets",
    "Explain the CAP theorem in simple terms with real-world database examples",
    "Create an Nginx configuration for reverse proxying to multiple backend services",
    "Write a technical email to the team explaining a recent production incident",
    "Implement a simple observer pattern in TypeScript",
    # --- Tutorials / moderate explanations ---
    "Write a short tutorial on using Python virtual environments",
    "Create a React custom hook for handling form state and validation",
    "Explain the difference between horizontal and vertical scaling with examples",
    "Write a comprehensive README for an open source Python library",
    "Implement retry logic with exponential backoff in Python",
    "Create a Prometheus alert rule for high error rates and latency",
    "Write a function to detect cycles in a linked list using Floyd's algorithm",
    "Explain database normalization up to 3NF with examples",
    "Create a simple CLI tool in Python using argparse with subcommands",
    "Write a technical specification for a user notification feature",
    # --- Debugging / fixing (moderate scope, single issue) ---
    "Debug this SQL query that returns incorrect results due to a GROUP BY issue",
    "Implement a simple task queue with priority support in Python",
    "Write a script to set up a new development environment with all necessary tools",
    "Explain how OAuth 2.0 authorization code flow works with a sequence diagram",
    "Create a Python dataclass hierarchy for a library management system",
    "Write a comprehensive .gitignore file for a full-stack project and explain each entry",
    "Implement a simple LRU cache in Python using OrderedDict",
    "Debug this async Python function that sometimes hangs and explain why",
    "Write a migration guide from Class Components to React Hooks",
    "Create a Python script that monitors a directory for file changes and triggers actions",
    # --- Comparisons / analysis (moderate depth) ---
    "Explain the pros and cons of NoSQL vs SQL databases for different use cases",
    "Implement a Trie data structure for autocomplete functionality",
    "Write a comprehensive error handling strategy document for a REST API",
    "Create a CI pipeline configuration that includes linting, testing, and code coverage",
    "Fix this race condition in a multi-threaded Python program",
    "Write a function to convert between different date formats with timezone support",
    "Explain how container networking works in Docker and Kubernetes",
    "Create a simple plugin system in Python using abstract base classes",
    "Write a data visualization script using matplotlib to show sales trends",
    "Implement input validation and sanitization for a web form",
    # --- Documentation / planning ---
    "Write an ADR (Architecture Decision Record) for choosing a message queue",
    "Create a health check endpoint that tests database, cache, and external service connections",
    "Find and fix the memory leak in this Node.js event listener code",
    "Write a Python generator for paginating through large API responses",
    "Create a configuration management setup that supports multiple environments",
    "Explain the trade-offs between monorepo and polyrepo approaches",
    "Write a comprehensive API rate limiting strategy document",
    "Implement a simple circuit breaker pattern in Python",
    "Debug why this Docker container keeps crashing on startup",
    "Create a project scaffolding script that sets up a new microservice",
    "Write an end-to-end test for a login flow using Playwright",
    "Explain how B-trees work and why databases use them for indexing",
    "Create a webhook handler that validates signatures and processes events",
    "Write a performance benchmarking script for comparing two implementations",
    "Set up ESLint and Prettier for a TypeScript React project with custom rules",
    "Implement a feature flag system with percentage-based rollouts",
    "Write a database seed script with realistic test data for development",
    "Create a load testing script using k6 for an API endpoint",
    "Explain the differences between symmetric and asymmetric encryption with use cases",
    "Write a Python function to convert a Roman numeral string to an integer",
    # --- Business (non-SWE) ---
    "Draft a professional email declining a meeting invitation",
    "Summarize the key differences between LLC and S-Corp",
    "Create an agenda for a 30-minute team standup",
    "Write a SWOT analysis template for a small retail business",
    "Explain the difference between gross margin and net margin with examples",
    "Draft a one-page executive summary for a quarterly business review",
    # --- Legal (non-SWE) ---
    "Explain the key elements of a valid contract",
    "What are the main differences between a trademark and a copyright?",
    "Summarize the GDPR data subject rights",
    "Explain the difference between mediation and arbitration",
    "Describe the process of filing a small claims court case in the US",
    "What are the key provisions of the Fair Labor Standards Act?",
    # --- Creative (non-SWE) ---
    "Write a 200-word product description for a wireless speaker",
    "Create three tagline options for an eco-friendly clothing brand",
    "Write a short bio for a LinkedIn profile of a marketing manager",
    "Draft a compelling opening paragraph for a travel blog about Kyoto",
    "Write a 150-word elevator pitch for a meal delivery startup",
    "Create a character sketch for a detective in a noir novel",
    # --- Education (non-SWE) ---
    "Explain the causes of the French Revolution in 3 paragraphs",
    "Compare and contrast mitosis and meiosis",
    "Describe how supply and demand affects pricing with real-world examples",
    "Explain the water cycle and its importance to ecosystems",
    "Summarize the key events of the Cold War in chronological order",
    "Describe the structure of the US federal government with checks and balances",
    # --- Medical (non-SWE) ---
    "Explain the difference between Type 1 and Type 2 diabetes",
    "What are the common side effects of beta-blockers?",
    "Describe the stages of wound healing",
    "Explain how vaccines work and the concept of herd immunity",
    "Compare the symptoms of a heart attack vs a panic attack",
    "Describe the differences between MRI, CT scan, and X-ray imaging",
    # --- Finance (non-SWE) ---
    "Explain how a mortgage amortization schedule works",
    "Compare index funds vs actively managed funds",
    "What are the tax implications of converting a traditional IRA to a Roth?",
    "Explain the difference between term life and whole life insurance",
    "Describe how dollar-cost averaging works with a practical example",
    "What are the key factors that affect a FICO credit score?",
]

COMPLEX_PROTOTYPES = [
    "Design a microservices architecture for a real-time multiplayer game with matchmaking, leaderboards, and anti-cheat systems",
    "Architect a distributed event-sourcing system for a financial trading platform that handles millions of transactions per second",
    "Design a scalable notification system that supports push, email, SMS, and in-app channels with user preferences and rate limiting",
    "Create a system design for a URL shortener that handles 100 million daily requests with analytics",
    "Explain the trade-offs between consistency and availability in distributed systems, using real-world examples from companies like Netflix and Amazon",
    "Compare and contrast the CAP theorem implications for SQL vs NoSQL databases in a microservices context, then recommend an approach for an e-commerce platform",
    "Analyze the economic impacts of remote work adoption on urban real estate markets, transportation infrastructure, and local businesses",
    "Walk me through the reasoning behind choosing between a monolithic and microservices architecture for a startup's MVP",
    "Implement a thread-safe LRU cache in Python with TTL support, size limits, and cache statistics tracking",
    "Write a complete REST API with authentication, rate limiting, pagination, and comprehensive error handling using FastAPI",
    "Build a React component library with a design system that includes theming, accessibility, responsive design, and documentation",
    "Implement a B-tree data structure with insert, delete, search, and range query operations, including rebalancing",
    "Create a Python decorator that implements retry logic with exponential backoff, jitter, circuit breaking, and logging",
    "Debug this memory leak in a Node.js application that occurs during WebSocket connections under high concurrency, and explain the GC implications",
    "Optimize this SQL query that takes 30 seconds on a table with 50 million rows, considering indexing strategies, query plan analysis, and partitioning",
    "Profile and optimize a Python data pipeline that processes 10GB CSV files, currently taking 4 hours to complete",
    "Compare the latest transformer architectures (GPT-4, Claude, Gemini, Llama) in terms of training methodology, context handling, and real-world performance benchmarks",
    "Synthesize the current research on quantum error correction and explain the implications for practical quantum computing timelines",
    "Analyze the trade-offs between different consensus algorithms (Paxos, Raft, PBFT) for blockchain applications",
    "Write a short story exploring the ethical implications of AI consciousness, incorporating themes from both Eastern and Western philosophy",
    "Create a detailed fictional world with its own political system, economy, religion, and history spanning 1000 years",
    "Write a technical blog post explaining category theory concepts using cooking metaphors, targeted at software engineers",
    "Prove that the halting problem is undecidable using a diagonalization argument, and explain the practical implications for software verification",
    "Derive the backpropagation algorithm from first principles and explain how automatic differentiation relates to it",
    "Prove the correctness of Dijkstra's algorithm and analyze its time complexity under different priority queue implementations",
    "Design a database schema for a social media platform, then write migration scripts, explain indexing strategy, outline the caching layer, and describe the data archival process",
    "Create a complete CI/CD pipeline configuration including build, test, security scanning, staging deployment, canary releases, and rollback procedures",
    "Build a comprehensive monitoring and alerting system covering application metrics, infrastructure health, business KPIs, and incident response automation",
    "Perform a security audit of this authentication flow, identifying potential vulnerabilities including OWASP Top 10 risks, and recommend mitigations with code examples",
    "Design a zero-trust security architecture for a multi-cloud environment with on-premises legacy systems",
    "Analyze the security implications of implementing OAuth 2.0 with PKCE for a mobile application, including threat modeling",
    "Develop a technical migration strategy to move a monolithic PHP application to a cloud-native architecture, including timeline, risk assessment, and team structure",
    "Create a comprehensive data strategy for a healthcare company transitioning to AI-driven diagnostics, addressing privacy, compliance, and technical infrastructure",
    "Design a disaster recovery plan for a financial services company with RPO of 15 minutes and RTO of 1 hour across multiple regions",
    "Analyze the performance characteristics of different garbage collection algorithms and recommend the optimal GC configuration for a latency-sensitive trading system",
    "Compare container orchestration approaches (Kubernetes, Nomad, ECS) for a company running 500 microservices across three cloud providers",
    "Evaluate the trade-offs of different state management solutions in a large-scale React application with offline-first requirements",
    "Refactor this 2000-line God class into a proper domain-driven design with bounded contexts, aggregates, and event handlers",
    "Review this distributed transaction implementation for correctness, identify race conditions, and propose a saga pattern alternative",
    "Analyze this machine learning pipeline for data leakage, feature engineering issues, and suggest improvements to the model evaluation strategy",
    "Explain how principles from control theory apply to designing auto-scaling systems, with specific implementation recommendations",
    "Connect concepts from game theory to microservices communication patterns and explain how to prevent cascade failures",
    "Apply information theory concepts to optimize data compression in a real-time video streaming architecture",
    "Diagnose why this Kubernetes cluster experiences intermittent pod evictions during peak traffic, analyzing resource limits, node pressure, and scheduler behavior",
    "Investigate a race condition in this concurrent Go program that only manifests under specific timing conditions with high CPU load",
    "Troubleshoot why this distributed cache shows inconsistent reads after network partitions despite using quorum-based replication",
    "Refactor the authentication system from JWT to session-based auth, updating all middleware, routes, and tests across the codebase",
    "Migrate this Express.js app to use TypeScript, converting all files, adding type definitions, and updating the build pipeline",
    "Split this monolithic app.py into a proper package structure with separate modules for routes, models, services, and utils",
    "The deploy is failing in CI — check the GitHub Actions logs, find the error, trace it back to the source file, and fix it",
    "Users are reporting 500 errors on the /api/checkout endpoint — check the logs, reproduce the issue, identify the root cause, and implement a fix",
    "The app is consuming 4GB of memory in production — profile the application, identify the memory leak, and fix it",
    "Read the existing database schema, then implement a new feature for user notifications with migrations, models, API endpoints, and WebSocket support",
    "Look at how authentication works in this codebase, then add OAuth2 login with Google and GitHub providers, including callback handlers and token refresh",
    "Analyze the current test suite, identify gaps in coverage, and write integration tests for all untested API endpoints",
    "Set up a complete development environment: clone the repo, install dependencies, configure the database, run migrations, seed test data, and verify everything works",
    "Create a new microservice that integrates with the existing API gateway — scaffold the project, implement the service, add Docker config, update the gateway routes, and write deployment manifests",
    "Audit all dependencies for security vulnerabilities, update the vulnerable ones, verify no breaking changes, and update the lockfile",
    "Analyze the current database query patterns, identify the N+1 queries, and refactor the ORM layer to use eager loading with proper join strategies",
    "Review the error handling across the entire API, standardize the error response format, add proper error codes, and implement a global exception handler",
    "Evaluate whether we should migrate from REST to GraphQL for this project, analyze the current endpoints, and create a migration plan with schema design",
    "Scrape the documentation site, extract all API endpoints and their parameters, generate TypeScript types, and create an API client library",
    "Monitor this web application for performance regressions — set up Lighthouse CI, configure budgets, and create alerts for Core Web Vitals degradation",
    # --- Business (non-SWE) ---
    "Develop a go-to-market strategy for a B2B SaaS product entering the European healthcare market, considering GDPR compliance, local competitors, and pricing for different country tiers",
    "Analyze the competitive dynamics between Uber and Lyft, including network effects, unit economics, regulatory moats, and predict which strategic moves each should make in the next 2 years",
    "Create a comprehensive business plan for a direct-to-consumer subscription box company, including market sizing, unit economics, customer acquisition strategy, retention modeling, and 5-year financial projections",
    "Develop a post-merger integration playbook for combining two mid-size insurance companies, covering organizational structure, technology consolidation, regulatory filings, customer communication, and cultural alignment",
    "Design a comprehensive employee retention strategy for a 500-person tech company experiencing 30% annual turnover, including compensation benchmarking, career pathing, culture initiatives, and ROI projections",
    # --- Legal (non-SWE) ---
    "Draft a comprehensive data processing agreement for a SaaS company that processes EU citizen data, covering all GDPR Article 28 requirements, sub-processor management, breach notification, and cross-border transfer mechanisms",
    "Analyze the legal implications of using AI-generated content in commercial products, covering copyright ownership, fair use, liability for hallucinated facts, and emerging regulations across US, EU, and UK",
    "Develop a comprehensive intellectual property protection strategy for a biotech startup, covering patent filing strategy across multiple jurisdictions, trade secret policies, employee IP assignment agreements, and licensing frameworks",
    "Analyze the regulatory landscape for launching a cryptocurrency exchange in the US, covering SEC, CFTC, FinCEN requirements, state money transmitter licenses, AML/KYC obligations, and ongoing compliance frameworks",
    "Draft a comprehensive terms of service and privacy policy for a health-tech platform that collects biometric data, addressing HIPAA, state biometric privacy laws, CCPA, and international data transfer requirements",
    # --- Creative (non-SWE) ---
    "Write a 2000-word short story about a time traveler who discovers that every change they make to the past creates an alternate timeline they can never return to, exploring themes of loss, identity, and the irreversibility of choice",
    "Develop a comprehensive brand identity guide for a premium sustainable fashion brand, including voice, tone, visual language, messaging framework for different audiences, and sample copy for website, social media, and email",
    "Write a pilot episode script for a dark comedy TV series set in a struggling newspaper office during the rise of digital media, including character bibles for six main characters, episode outline, and three sample scenes with dialogue",
    "Create a complete marketing campaign for a non-profit climate organization targeting Gen Z, including campaign concept, messaging hierarchy, content calendar for 3 months across 5 platforms, influencer strategy, and KPI framework",
    "Develop a comprehensive worldbuilding document for a fantasy novel series, including geography, political systems, magic system with rules and limitations, economic structures, religious traditions, and a 500-year historical timeline",
    # --- Education (non-SWE) ---
    "Design a complete 12-week university course syllabus on machine learning, including weekly topics, readings, programming assignments with rubrics, a midterm project, final exam format, and accommodation policies",
    "Create a comprehensive K-12 curriculum framework for teaching financial literacy, with age-appropriate modules for elementary, middle, and high school, including lesson plans, assessment rubrics, parent engagement strategies, and alignment with state standards",
    "Develop a detailed proposal for transforming a traditional lecture-based biology program into a flipped classroom model, including technology requirements, faculty training plan, student support structures, assessment redesign, and a phased 2-year implementation timeline",
    "Design an adaptive learning system for teaching calculus that personalizes content based on student performance, including prerequisite mapping, diagnostic assessments, learning path algorithms, intervention triggers, and effectiveness measurement methodology",
    # --- Finance (non-SWE) ---
    "Build a detailed financial model for a Series A startup, including 3-year revenue projections with cohort analysis, burn rate scenarios, dilution modeling for the next two rounds, and sensitivity analysis on key assumptions",
    "Develop a comprehensive retirement planning strategy for a 45-year-old dual-income household earning $300K combined, with $500K in existing investments, two children approaching college age, covering tax optimization, asset allocation, Social Security timing, healthcare bridge strategy, and estate planning considerations",
    "Create a detailed risk management framework for a $50M hedge fund, including VaR modeling, stress testing scenarios, counterparty risk assessment, liquidity management, regulatory capital requirements, and automated alert thresholds",
    "Analyze the financial viability of a commercial real estate development project, including land acquisition, construction cost modeling, absorption rate projections, cap rate analysis, debt structuring options, tax implications including cost segregation, and exit strategy comparison",
    "Design a comprehensive ESG investment framework for an institutional investor, including screening criteria, scoring methodology, portfolio construction constraints, engagement strategy for underperforming holdings, and reporting standards alignment with TCFD and SASB",
    # --- Medical (non-SWE) ---
    "Develop a differential diagnosis framework for a patient presenting with acute chest pain, fatigue, and elevated troponin, considering cardiac, pulmonary, gastrointestinal, and musculoskeletal etiologies, with recommended diagnostic workup for each",
    "Design a comprehensive clinical trial protocol for a Phase III study of a novel immunotherapy drug for treatment-resistant melanoma, including patient selection criteria, randomization strategy, primary and secondary endpoints, safety monitoring plan, statistical analysis plan, and interim analysis triggers",
    "Create a detailed public health response plan for a novel respiratory pathogen outbreak in a metropolitan area, covering surveillance systems, contact tracing logistics, healthcare surge capacity planning, communication strategy for diverse populations, vaccine distribution prioritization, and economic impact mitigation",
    "Develop a comprehensive chronic disease management program for Type 2 diabetes in an underserved community, including patient identification, care team structure, clinical protocols, technology platform requirements, behavioral health integration, cultural competency training, outcome metrics, and sustainable funding model",
    # --- Science / Research (non-SWE) ---
    "Write a comprehensive literature review on CRISPR-Cas9 gene editing applications in treating genetic disorders, covering current clinical trials, delivery mechanism challenges, off-target effects, ethical considerations, regulatory frameworks across different countries, and projections for therapeutic applications in the next decade",
    "Design a research methodology for studying the long-term cognitive effects of social media use on adolescents, including study design, participant recruitment strategy, control variables, measurement instruments, longitudinal data collection plan, ethical review considerations, and statistical analysis approach",
]
